do

    HERO_BLADEMASTER_TYPE_ID             = FourCC("H000")
    HERO_BANSHEE_RANGER_TYPE_ID          = FourCC("H001")
    HERO_WARDEN_TYPE_ID                  = FourCC("H002")
    HERO_DEMON_HUNTER_TYPE_ID            = FourCC("H003")
    HERO_TAUREN_CHIEFTAIN_TYPE_ID        = FourCC("H004")
    HERO_SHADOW_HUNTER_TYPE_ID           = FourCC("H005")
    HERO_PANDAREN_BREWMASTER_TYPE_ID     = FourCC("H006")
    HERO_FARSEER_TYPE_ID                 = FourCC("H007")
    HERO_BEASTMASTER_TYPE_ID             = FourCC("H008")
    HERO_CRYPT_LORD_TYPE_ID              = FourCC("H009")
    HERO_DREAD_LORD_TYPE_ID              = FourCC("H00:")
    HERO_FLAME_LORD_TYPE_ID              = FourCC("H00;")
    HERO_LICH_TYPE_ID                    = FourCC("H00<")
    HERO_PRIESTESS_OF_THE_MOON_TYPE_ID   = FourCC("H00=")
    HERO_TINKER_TYPE_ID                  = FourCC("H00>")
    HERO_ALCHEMIST_TYPE_ID               = FourCC("H00?")
    HERO_ELDER_DRANAI_TYPE_ID            = FourCC("H00@")
    HERO_NAGA_TYPE_ID                    = FourCC("H00A")
    HERO_ADMIRAL_TYPE_ID                 = FourCC("H00B")
    HERO_ARCH_MAGE_TYPE_ID               = FourCC("H00C")
    HERO_MOUNTAIN_KING_TYPE_ID           = FourCC("H00D")
    HERO_TRACKER_TYPE_ID                 = FourCC("H00E")
    HERO_BLOOD_ELF_TYPE_ID               = FourCC("H00F")
    HERO_PALADIN_TYPE_ID                 = FourCC("H00G")
    HERO_DREAD_KNIGHT_TYPE_ID            = FourCC("H00H")
    HERO_ARCH_MAGE_TYPE_ID               = FourCC("H00I")

end

