---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by scopt.
--- DateTime: 14.03.2021 1:01
---

require 'build' {
    game = "C:\\Program Files (x86)\\Warcraft III\\_retail_\\x86_64",
    project = "D:\\Users\\scopterectus\\Documents\\Warcraft III\\Maps\\Test\\Mok-HD",
    map = "map.w3x",
    src = "src",
    run = nil
}

