---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by scopt.
--- DateTime: 14.03.2021 2:21
---

do

    S2FourCC = function( value )
        return string.unpack( ">I4", id )
    end

    FourCC2S = function( value )
        return string.pack( ">I4", id )
    end

end

